services:
  - type: web
    name: llm-query-system
    env: python
    plan: free # Or your preferred plan
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: BEARER_TOKEN
        sync: false
